.globl tp_mktf
.globl handle_int_0
handle_int_0:
	pushl $0
	pushl $0
	jmp tp_mktf
.globl handle_int_1
handle_int_1:
	pushl $0
	pushl $1
	jmp tp_mktf
.globl handle_int_2
handle_int_2:
	pushl $0
	pushl $2
	jmp tp_mktf
.globl handle_int_3
handle_int_3:
	pushl $0
	pushl $3
	jmp tp_mktf
.globl handle_int_4
handle_int_4:
	pushl $0
	pushl $4
	jmp tp_mktf
.globl handle_int_5
handle_int_5:
	pushl $0
	pushl $5
	jmp tp_mktf
.globl handle_int_6
handle_int_6:
	pushl $0
	pushl $6
	jmp tp_mktf
.globl handle_int_7
handle_int_7:
	pushl $0
	pushl $7
	jmp tp_mktf
.globl handle_int_8
handle_int_8:
	pushl $8
	jmp tp_mktf
.globl handle_int_9
handle_int_9:
	pushl $0
	pushl $9
	jmp tp_mktf
.globl handle_int_10
handle_int_10:
	pushl $10
	jmp tp_mktf
.globl handle_int_11
handle_int_11:
	pushl $11
	jmp tp_mktf
.globl handle_int_12
handle_int_12:
	pushl $12
	jmp tp_mktf
.globl handle_int_13
handle_int_13:
	pushl $13
	jmp tp_mktf
.globl handle_int_14
handle_int_14:
	pushl $14
	jmp tp_mktf
.globl handle_int_15
handle_int_15:
	pushl $0
	pushl $15
	jmp tp_mktf
.globl handle_int_16
handle_int_16:
	pushl $0
	pushl $16
	jmp tp_mktf
.globl handle_int_17
handle_int_17:
	pushl $17
	jmp tp_mktf
.globl handle_int_18
handle_int_18:
	pushl $0
	pushl $18
	jmp tp_mktf
.globl handle_int_19
handle_int_19:
	pushl $0
	pushl $19
	jmp tp_mktf
.globl handle_int_20
handle_int_20:
	pushl $0
	pushl $20
	jmp tp_mktf
.globl handle_int_21
handle_int_21:
	pushl $0
	pushl $21
	jmp tp_mktf
.globl handle_int_22
handle_int_22:
	pushl $0
	pushl $22
	jmp tp_mktf
.globl handle_int_23
handle_int_23:
	pushl $0
	pushl $23
	jmp tp_mktf
.globl handle_int_24
handle_int_24:
	pushl $0
	pushl $24
	jmp tp_mktf
.globl handle_int_25
handle_int_25:
	pushl $0
	pushl $25
	jmp tp_mktf
.globl handle_int_26
handle_int_26:
	pushl $0
	pushl $26
	jmp tp_mktf
.globl handle_int_27
handle_int_27:
	pushl $0
	pushl $27
	jmp tp_mktf
.globl handle_int_28
handle_int_28:
	pushl $0
	pushl $28
	jmp tp_mktf
.globl handle_int_29
handle_int_29:
	pushl $0
	pushl $29
	jmp tp_mktf
.globl handle_int_30
handle_int_30:
	pushl $0
	pushl $30
	jmp tp_mktf
.globl handle_int_31
handle_int_31:
	pushl $0
	pushl $31
	jmp tp_mktf
.globl handle_int_32
handle_int_32:
	pushl $0
	pushl $32
	jmp tp_mktf
.globl handle_int_33
handle_int_33:
	pushl $0
	pushl $33
	jmp tp_mktf
.globl handle_int_34
handle_int_34:
	pushl $0
	pushl $34
	jmp tp_mktf
.globl handle_int_35
handle_int_35:
	pushl $0
	pushl $35
	jmp tp_mktf
.globl handle_int_36
handle_int_36:
	pushl $0
	pushl $36
	jmp tp_mktf
.globl handle_int_37
handle_int_37:
	pushl $0
	pushl $37
	jmp tp_mktf
.globl handle_int_38
handle_int_38:
	pushl $0
	pushl $38
	jmp tp_mktf
.globl handle_int_39
handle_int_39:
	pushl $0
	pushl $39
	jmp tp_mktf
.globl handle_int_40
handle_int_40:
	pushl $0
	pushl $40
	jmp tp_mktf
.globl handle_int_41
handle_int_41:
	pushl $0
	pushl $41
	jmp tp_mktf
.globl handle_int_42
handle_int_42:
	pushl $0
	pushl $42
	jmp tp_mktf
.globl handle_int_43
handle_int_43:
	pushl $0
	pushl $43
	jmp tp_mktf
.globl handle_int_44
handle_int_44:
	pushl $0
	pushl $44
	jmp tp_mktf
.globl handle_int_45
handle_int_45:
	pushl $0
	pushl $45
	jmp tp_mktf
.globl handle_int_46
handle_int_46:
	pushl $0
	pushl $46
	jmp tp_mktf
.globl handle_int_47
handle_int_47:
	pushl $0
	pushl $47
	jmp tp_mktf
.globl handle_int_48
handle_int_48:
	pushl $0
	pushl $48
	jmp tp_mktf
.globl handle_int_49
handle_int_49:
	pushl $0
	pushl $49
	jmp tp_mktf
.globl handle_int_50
handle_int_50:
	pushl $0
	pushl $50
	jmp tp_mktf
.globl handle_int_51
handle_int_51:
	pushl $0
	pushl $51
	jmp tp_mktf
.globl handle_int_52
handle_int_52:
	pushl $0
	pushl $52
	jmp tp_mktf
.globl handle_int_53
handle_int_53:
	pushl $0
	pushl $53
	jmp tp_mktf
.globl handle_int_54
handle_int_54:
	pushl $0
	pushl $54
	jmp tp_mktf
.globl handle_int_55
handle_int_55:
	pushl $0
	pushl $55
	jmp tp_mktf
.globl handle_int_56
handle_int_56:
	pushl $0
	pushl $56
	jmp tp_mktf
.globl handle_int_57
handle_int_57:
	pushl $0
	pushl $57
	jmp tp_mktf
.globl handle_int_58
handle_int_58:
	pushl $0
	pushl $58
	jmp tp_mktf
.globl handle_int_59
handle_int_59:
	pushl $0
	pushl $59
	jmp tp_mktf
.globl handle_int_60
handle_int_60:
	pushl $0
	pushl $60
	jmp tp_mktf
.globl handle_int_61
handle_int_61:
	pushl $0
	pushl $61
	jmp tp_mktf
.globl handle_int_62
handle_int_62:
	pushl $0
	pushl $62
	jmp tp_mktf
.globl handle_int_63
handle_int_63:
	pushl $0
	pushl $63
	jmp tp_mktf
.globl handle_int_64
handle_int_64:
	pushl $0
	pushl $64
	jmp tp_mktf
.globl handle_int_65
handle_int_65:
	pushl $0
	pushl $65
	jmp tp_mktf
.globl handle_int_66
handle_int_66:
	pushl $0
	pushl $66
	jmp tp_mktf
.globl handle_int_67
handle_int_67:
	pushl $0
	pushl $67
	jmp tp_mktf
.globl handle_int_68
handle_int_68:
	pushl $0
	pushl $68
	jmp tp_mktf
.globl handle_int_69
handle_int_69:
	pushl $0
	pushl $69
	jmp tp_mktf
.globl handle_int_70
handle_int_70:
	pushl $0
	pushl $70
	jmp tp_mktf
.globl handle_int_71
handle_int_71:
	pushl $0
	pushl $71
	jmp tp_mktf
.globl handle_int_72
handle_int_72:
	pushl $0
	pushl $72
	jmp tp_mktf
.globl handle_int_73
handle_int_73:
	pushl $0
	pushl $73
	jmp tp_mktf
.globl handle_int_74
handle_int_74:
	pushl $0
	pushl $74
	jmp tp_mktf
.globl handle_int_75
handle_int_75:
	pushl $0
	pushl $75
	jmp tp_mktf
.globl handle_int_76
handle_int_76:
	pushl $0
	pushl $76
	jmp tp_mktf
.globl handle_int_77
handle_int_77:
	pushl $0
	pushl $77
	jmp tp_mktf
.globl handle_int_78
handle_int_78:
	pushl $0
	pushl $78
	jmp tp_mktf
.globl handle_int_79
handle_int_79:
	pushl $0
	pushl $79
	jmp tp_mktf
.globl handle_int_80
handle_int_80:
	pushl $0
	pushl $80
	jmp tp_mktf
.globl handle_int_81
handle_int_81:
	pushl $0
	pushl $81
	jmp tp_mktf
.globl handle_int_82
handle_int_82:
	pushl $0
	pushl $82
	jmp tp_mktf
.globl handle_int_83
handle_int_83:
	pushl $0
	pushl $83
	jmp tp_mktf
.globl handle_int_84
handle_int_84:
	pushl $0
	pushl $84
	jmp tp_mktf
.globl handle_int_85
handle_int_85:
	pushl $0
	pushl $85
	jmp tp_mktf
.globl handle_int_86
handle_int_86:
	pushl $0
	pushl $86
	jmp tp_mktf
.globl handle_int_87
handle_int_87:
	pushl $0
	pushl $87
	jmp tp_mktf
.globl handle_int_88
handle_int_88:
	pushl $0
	pushl $88
	jmp tp_mktf
.globl handle_int_89
handle_int_89:
	pushl $0
	pushl $89
	jmp tp_mktf
.globl handle_int_90
handle_int_90:
	pushl $0
	pushl $90
	jmp tp_mktf
.globl handle_int_91
handle_int_91:
	pushl $0
	pushl $91
	jmp tp_mktf
.globl handle_int_92
handle_int_92:
	pushl $0
	pushl $92
	jmp tp_mktf
.globl handle_int_93
handle_int_93:
	pushl $0
	pushl $93
	jmp tp_mktf
.globl handle_int_94
handle_int_94:
	pushl $0
	pushl $94
	jmp tp_mktf
.globl handle_int_95
handle_int_95:
	pushl $0
	pushl $95
	jmp tp_mktf
.globl handle_int_96
handle_int_96:
	pushl $0
	pushl $96
	jmp tp_mktf
.globl handle_int_97
handle_int_97:
	pushl $0
	pushl $97
	jmp tp_mktf
.globl handle_int_98
handle_int_98:
	pushl $0
	pushl $98
	jmp tp_mktf
.globl handle_int_99
handle_int_99:
	pushl $0
	pushl $99
	jmp tp_mktf
.globl handle_int_100
handle_int_100:
	pushl $0
	pushl $100
	jmp tp_mktf
.globl handle_int_101
handle_int_101:
	pushl $0
	pushl $101
	jmp tp_mktf
.globl handle_int_102
handle_int_102:
	pushl $0
	pushl $102
	jmp tp_mktf
.globl handle_int_103
handle_int_103:
	pushl $0
	pushl $103
	jmp tp_mktf
.globl handle_int_104
handle_int_104:
	pushl $0
	pushl $104
	jmp tp_mktf
.globl handle_int_105
handle_int_105:
	pushl $0
	pushl $105
	jmp tp_mktf
.globl handle_int_106
handle_int_106:
	pushl $0
	pushl $106
	jmp tp_mktf
.globl handle_int_107
handle_int_107:
	pushl $0
	pushl $107
	jmp tp_mktf
.globl handle_int_108
handle_int_108:
	pushl $0
	pushl $108
	jmp tp_mktf
.globl handle_int_109
handle_int_109:
	pushl $0
	pushl $109
	jmp tp_mktf
.globl handle_int_110
handle_int_110:
	pushl $0
	pushl $110
	jmp tp_mktf
.globl handle_int_111
handle_int_111:
	pushl $0
	pushl $111
	jmp tp_mktf
.globl handle_int_112
handle_int_112:
	pushl $0
	pushl $112
	jmp tp_mktf
.globl handle_int_113
handle_int_113:
	pushl $0
	pushl $113
	jmp tp_mktf
.globl handle_int_114
handle_int_114:
	pushl $0
	pushl $114
	jmp tp_mktf
.globl handle_int_115
handle_int_115:
	pushl $0
	pushl $115
	jmp tp_mktf
.globl handle_int_116
handle_int_116:
	pushl $0
	pushl $116
	jmp tp_mktf
.globl handle_int_117
handle_int_117:
	pushl $0
	pushl $117
	jmp tp_mktf
.globl handle_int_118
handle_int_118:
	pushl $0
	pushl $118
	jmp tp_mktf
.globl handle_int_119
handle_int_119:
	pushl $0
	pushl $119
	jmp tp_mktf
.globl handle_int_120
handle_int_120:
	pushl $0
	pushl $120
	jmp tp_mktf
.globl handle_int_121
handle_int_121:
	pushl $0
	pushl $121
	jmp tp_mktf
.globl handle_int_122
handle_int_122:
	pushl $0
	pushl $122
	jmp tp_mktf
.globl handle_int_123
handle_int_123:
	pushl $0
	pushl $123
	jmp tp_mktf
.globl handle_int_124
handle_int_124:
	pushl $0
	pushl $124
	jmp tp_mktf
.globl handle_int_125
handle_int_125:
	pushl $0
	pushl $125
	jmp tp_mktf
.globl handle_int_126
handle_int_126:
	pushl $0
	pushl $126
	jmp tp_mktf
.globl handle_int_127
handle_int_127:
	pushl $0
	pushl $127
	jmp tp_mktf
.globl handle_int_128
handle_int_128:
	pushl $0
	pushl $128
	jmp tp_mktf
.globl handle_int_129
handle_int_129:
	pushl $0
	pushl $129
	jmp tp_mktf
.globl handle_int_130
handle_int_130:
	pushl $0
	pushl $130
	jmp tp_mktf
.globl handle_int_131
handle_int_131:
	pushl $0
	pushl $131
	jmp tp_mktf
.globl handle_int_132
handle_int_132:
	pushl $0
	pushl $132
	jmp tp_mktf
.globl handle_int_133
handle_int_133:
	pushl $0
	pushl $133
	jmp tp_mktf
.globl handle_int_134
handle_int_134:
	pushl $0
	pushl $134
	jmp tp_mktf
.globl handle_int_135
handle_int_135:
	pushl $0
	pushl $135
	jmp tp_mktf
.globl handle_int_136
handle_int_136:
	pushl $0
	pushl $136
	jmp tp_mktf
.globl handle_int_137
handle_int_137:
	pushl $0
	pushl $137
	jmp tp_mktf
.globl handle_int_138
handle_int_138:
	pushl $0
	pushl $138
	jmp tp_mktf
.globl handle_int_139
handle_int_139:
	pushl $0
	pushl $139
	jmp tp_mktf
.globl handle_int_140
handle_int_140:
	pushl $0
	pushl $140
	jmp tp_mktf
.globl handle_int_141
handle_int_141:
	pushl $0
	pushl $141
	jmp tp_mktf
.globl handle_int_142
handle_int_142:
	pushl $0
	pushl $142
	jmp tp_mktf
.globl handle_int_143
handle_int_143:
	pushl $0
	pushl $143
	jmp tp_mktf
.globl handle_int_144
handle_int_144:
	pushl $0
	pushl $144
	jmp tp_mktf
.globl handle_int_145
handle_int_145:
	pushl $0
	pushl $145
	jmp tp_mktf
.globl handle_int_146
handle_int_146:
	pushl $0
	pushl $146
	jmp tp_mktf
.globl handle_int_147
handle_int_147:
	pushl $0
	pushl $147
	jmp tp_mktf
.globl handle_int_148
handle_int_148:
	pushl $0
	pushl $148
	jmp tp_mktf
.globl handle_int_149
handle_int_149:
	pushl $0
	pushl $149
	jmp tp_mktf
.globl handle_int_150
handle_int_150:
	pushl $0
	pushl $150
	jmp tp_mktf
.globl handle_int_151
handle_int_151:
	pushl $0
	pushl $151
	jmp tp_mktf
.globl handle_int_152
handle_int_152:
	pushl $0
	pushl $152
	jmp tp_mktf
.globl handle_int_153
handle_int_153:
	pushl $0
	pushl $153
	jmp tp_mktf
.globl handle_int_154
handle_int_154:
	pushl $0
	pushl $154
	jmp tp_mktf
.globl handle_int_155
handle_int_155:
	pushl $0
	pushl $155
	jmp tp_mktf
.globl handle_int_156
handle_int_156:
	pushl $0
	pushl $156
	jmp tp_mktf
.globl handle_int_157
handle_int_157:
	pushl $0
	pushl $157
	jmp tp_mktf
.globl handle_int_158
handle_int_158:
	pushl $0
	pushl $158
	jmp tp_mktf
.globl handle_int_159
handle_int_159:
	pushl $0
	pushl $159
	jmp tp_mktf
.globl handle_int_160
handle_int_160:
	pushl $0
	pushl $160
	jmp tp_mktf
.globl handle_int_161
handle_int_161:
	pushl $0
	pushl $161
	jmp tp_mktf
.globl handle_int_162
handle_int_162:
	pushl $0
	pushl $162
	jmp tp_mktf
.globl handle_int_163
handle_int_163:
	pushl $0
	pushl $163
	jmp tp_mktf
.globl handle_int_164
handle_int_164:
	pushl $0
	pushl $164
	jmp tp_mktf
.globl handle_int_165
handle_int_165:
	pushl $0
	pushl $165
	jmp tp_mktf
.globl handle_int_166
handle_int_166:
	pushl $0
	pushl $166
	jmp tp_mktf
.globl handle_int_167
handle_int_167:
	pushl $0
	pushl $167
	jmp tp_mktf
.globl handle_int_168
handle_int_168:
	pushl $0
	pushl $168
	jmp tp_mktf
.globl handle_int_169
handle_int_169:
	pushl $0
	pushl $169
	jmp tp_mktf
.globl handle_int_170
handle_int_170:
	pushl $0
	pushl $170
	jmp tp_mktf
.globl handle_int_171
handle_int_171:
	pushl $0
	pushl $171
	jmp tp_mktf
.globl handle_int_172
handle_int_172:
	pushl $0
	pushl $172
	jmp tp_mktf
.globl handle_int_173
handle_int_173:
	pushl $0
	pushl $173
	jmp tp_mktf
.globl handle_int_174
handle_int_174:
	pushl $0
	pushl $174
	jmp tp_mktf
.globl handle_int_175
handle_int_175:
	pushl $0
	pushl $175
	jmp tp_mktf
.globl handle_int_176
handle_int_176:
	pushl $0
	pushl $176
	jmp tp_mktf
.globl handle_int_177
handle_int_177:
	pushl $0
	pushl $177
	jmp tp_mktf
.globl handle_int_178
handle_int_178:
	pushl $0
	pushl $178
	jmp tp_mktf
.globl handle_int_179
handle_int_179:
	pushl $0
	pushl $179
	jmp tp_mktf
.globl handle_int_180
handle_int_180:
	pushl $0
	pushl $180
	jmp tp_mktf
.globl handle_int_181
handle_int_181:
	pushl $0
	pushl $181
	jmp tp_mktf
.globl handle_int_182
handle_int_182:
	pushl $0
	pushl $182
	jmp tp_mktf
.globl handle_int_183
handle_int_183:
	pushl $0
	pushl $183
	jmp tp_mktf
.globl handle_int_184
handle_int_184:
	pushl $0
	pushl $184
	jmp tp_mktf
.globl handle_int_185
handle_int_185:
	pushl $0
	pushl $185
	jmp tp_mktf
.globl handle_int_186
handle_int_186:
	pushl $0
	pushl $186
	jmp tp_mktf
.globl handle_int_187
handle_int_187:
	pushl $0
	pushl $187
	jmp tp_mktf
.globl handle_int_188
handle_int_188:
	pushl $0
	pushl $188
	jmp tp_mktf
.globl handle_int_189
handle_int_189:
	pushl $0
	pushl $189
	jmp tp_mktf
.globl handle_int_190
handle_int_190:
	pushl $0
	pushl $190
	jmp tp_mktf
.globl handle_int_191
handle_int_191:
	pushl $0
	pushl $191
	jmp tp_mktf
.globl handle_int_192
handle_int_192:
	pushl $0
	pushl $192
	jmp tp_mktf
.globl handle_int_193
handle_int_193:
	pushl $0
	pushl $193
	jmp tp_mktf
.globl handle_int_194
handle_int_194:
	pushl $0
	pushl $194
	jmp tp_mktf
.globl handle_int_195
handle_int_195:
	pushl $0
	pushl $195
	jmp tp_mktf
.globl handle_int_196
handle_int_196:
	pushl $0
	pushl $196
	jmp tp_mktf
.globl handle_int_197
handle_int_197:
	pushl $0
	pushl $197
	jmp tp_mktf
.globl handle_int_198
handle_int_198:
	pushl $0
	pushl $198
	jmp tp_mktf
.globl handle_int_199
handle_int_199:
	pushl $0
	pushl $199
	jmp tp_mktf
.globl handle_int_200
handle_int_200:
	pushl $0
	pushl $200
	jmp tp_mktf
.globl handle_int_201
handle_int_201:
	pushl $0
	pushl $201
	jmp tp_mktf
.globl handle_int_202
handle_int_202:
	pushl $0
	pushl $202
	jmp tp_mktf
.globl handle_int_203
handle_int_203:
	pushl $0
	pushl $203
	jmp tp_mktf
.globl handle_int_204
handle_int_204:
	pushl $0
	pushl $204
	jmp tp_mktf
.globl handle_int_205
handle_int_205:
	pushl $0
	pushl $205
	jmp tp_mktf
.globl handle_int_206
handle_int_206:
	pushl $0
	pushl $206
	jmp tp_mktf
.globl handle_int_207
handle_int_207:
	pushl $0
	pushl $207
	jmp tp_mktf
.globl handle_int_208
handle_int_208:
	pushl $0
	pushl $208
	jmp tp_mktf
.globl handle_int_209
handle_int_209:
	pushl $0
	pushl $209
	jmp tp_mktf
.globl handle_int_210
handle_int_210:
	pushl $0
	pushl $210
	jmp tp_mktf
.globl handle_int_211
handle_int_211:
	pushl $0
	pushl $211
	jmp tp_mktf
.globl handle_int_212
handle_int_212:
	pushl $0
	pushl $212
	jmp tp_mktf
.globl handle_int_213
handle_int_213:
	pushl $0
	pushl $213
	jmp tp_mktf
.globl handle_int_214
handle_int_214:
	pushl $0
	pushl $214
	jmp tp_mktf
.globl handle_int_215
handle_int_215:
	pushl $0
	pushl $215
	jmp tp_mktf
.globl handle_int_216
handle_int_216:
	pushl $0
	pushl $216
	jmp tp_mktf
.globl handle_int_217
handle_int_217:
	pushl $0
	pushl $217
	jmp tp_mktf
.globl handle_int_218
handle_int_218:
	pushl $0
	pushl $218
	jmp tp_mktf
.globl handle_int_219
handle_int_219:
	pushl $0
	pushl $219
	jmp tp_mktf
.globl handle_int_220
handle_int_220:
	pushl $0
	pushl $220
	jmp tp_mktf
.globl handle_int_221
handle_int_221:
	pushl $0
	pushl $221
	jmp tp_mktf
.globl handle_int_222
handle_int_222:
	pushl $0
	pushl $222
	jmp tp_mktf
.globl handle_int_223
handle_int_223:
	pushl $0
	pushl $223
	jmp tp_mktf
.globl handle_int_224
handle_int_224:
	pushl $0
	pushl $224
	jmp tp_mktf
.globl handle_int_225
handle_int_225:
	pushl $0
	pushl $225
	jmp tp_mktf
.globl handle_int_226
handle_int_226:
	pushl $0
	pushl $226
	jmp tp_mktf
.globl handle_int_227
handle_int_227:
	pushl $0
	pushl $227
	jmp tp_mktf
.globl handle_int_228
handle_int_228:
	pushl $0
	pushl $228
	jmp tp_mktf
.globl handle_int_229
handle_int_229:
	pushl $0
	pushl $229
	jmp tp_mktf
.globl handle_int_230
handle_int_230:
	pushl $0
	pushl $230
	jmp tp_mktf
.globl handle_int_231
handle_int_231:
	pushl $0
	pushl $231
	jmp tp_mktf
.globl handle_int_232
handle_int_232:
	pushl $0
	pushl $232
	jmp tp_mktf
.globl handle_int_233
handle_int_233:
	pushl $0
	pushl $233
	jmp tp_mktf
.globl handle_int_234
handle_int_234:
	pushl $0
	pushl $234
	jmp tp_mktf
.globl handle_int_235
handle_int_235:
	pushl $0
	pushl $235
	jmp tp_mktf
.globl handle_int_236
handle_int_236:
	pushl $0
	pushl $236
	jmp tp_mktf
.globl handle_int_237
handle_int_237:
	pushl $0
	pushl $237
	jmp tp_mktf
.globl handle_int_238
handle_int_238:
	pushl $0
	pushl $238
	jmp tp_mktf
.globl handle_int_239
handle_int_239:
	pushl $0
	pushl $239
	jmp tp_mktf
.globl handle_int_240
handle_int_240:
	pushl $0
	pushl $240
	jmp tp_mktf
.globl handle_int_241
handle_int_241:
	pushl $0
	pushl $241
	jmp tp_mktf
.globl handle_int_242
handle_int_242:
	pushl $0
	pushl $242
	jmp tp_mktf
.globl handle_int_243
handle_int_243:
	pushl $0
	pushl $243
	jmp tp_mktf
.globl handle_int_244
handle_int_244:
	pushl $0
	pushl $244
	jmp tp_mktf
.globl handle_int_245
handle_int_245:
	pushl $0
	pushl $245
	jmp tp_mktf
.globl handle_int_246
handle_int_246:
	pushl $0
	pushl $246
	jmp tp_mktf
.globl handle_int_247
handle_int_247:
	pushl $0
	pushl $247
	jmp tp_mktf
.globl handle_int_248
handle_int_248:
	pushl $0
	pushl $248
	jmp tp_mktf
.globl handle_int_249
handle_int_249:
	pushl $0
	pushl $249
	jmp tp_mktf
.globl handle_int_250
handle_int_250:
	pushl $0
	pushl $250
	jmp tp_mktf
.globl handle_int_251
handle_int_251:
	pushl $0
	pushl $251
	jmp tp_mktf
.globl handle_int_252
handle_int_252:
	pushl $0
	pushl $252
	jmp tp_mktf
.globl handle_int_253
handle_int_253:
	pushl $0
	pushl $253
	jmp tp_mktf
.globl handle_int_254
handle_int_254:
	pushl $0
	pushl $254
	jmp tp_mktf
.data
.globl trap_handlers
trap_handlers:
	.long handle_int_0
	.long handle_int_1
	.long handle_int_2
	.long handle_int_3
	.long handle_int_4
	.long handle_int_5
	.long handle_int_6
	.long handle_int_7
	.long handle_int_8
	.long handle_int_9
	.long handle_int_10
	.long handle_int_11
	.long handle_int_12
	.long handle_int_13
	.long handle_int_14
	.long handle_int_15
	.long handle_int_16
	.long handle_int_17
	.long handle_int_18
	.long handle_int_19
	.long handle_int_20
	.long handle_int_21
	.long handle_int_22
	.long handle_int_23
	.long handle_int_24
	.long handle_int_25
	.long handle_int_26
	.long handle_int_27
	.long handle_int_28
	.long handle_int_29
	.long handle_int_30
	.long handle_int_31
	.long handle_int_32
	.long handle_int_33
	.long handle_int_34
	.long handle_int_35
	.long handle_int_36
	.long handle_int_37
	.long handle_int_38
	.long handle_int_39
	.long handle_int_40
	.long handle_int_41
	.long handle_int_42
	.long handle_int_43
	.long handle_int_44
	.long handle_int_45
	.long handle_int_46
	.long handle_int_47
	.long handle_int_48
	.long handle_int_49
	.long handle_int_50
	.long handle_int_51
	.long handle_int_52
	.long handle_int_53
	.long handle_int_54
	.long handle_int_55
	.long handle_int_56
	.long handle_int_57
	.long handle_int_58
	.long handle_int_59
	.long handle_int_60
	.long handle_int_61
	.long handle_int_62
	.long handle_int_63
	.long handle_int_64
	.long handle_int_65
	.long handle_int_66
	.long handle_int_67
	.long handle_int_68
	.long handle_int_69
	.long handle_int_70
	.long handle_int_71
	.long handle_int_72
	.long handle_int_73
	.long handle_int_74
	.long handle_int_75
	.long handle_int_76
	.long handle_int_77
	.long handle_int_78
	.long handle_int_79
	.long handle_int_80
	.long handle_int_81
	.long handle_int_82
	.long handle_int_83
	.long handle_int_84
	.long handle_int_85
	.long handle_int_86
	.long handle_int_87
	.long handle_int_88
	.long handle_int_89
	.long handle_int_90
	.long handle_int_91
	.long handle_int_92
	.long handle_int_93
	.long handle_int_94
	.long handle_int_95
	.long handle_int_96
	.long handle_int_97
	.long handle_int_98
	.long handle_int_99
	.long handle_int_100
	.long handle_int_101
	.long handle_int_102
	.long handle_int_103
	.long handle_int_104
	.long handle_int_105
	.long handle_int_106
	.long handle_int_107
	.long handle_int_108
	.long handle_int_109
	.long handle_int_110
	.long handle_int_111
	.long handle_int_112
	.long handle_int_113
	.long handle_int_114
	.long handle_int_115
	.long handle_int_116
	.long handle_int_117
	.long handle_int_118
	.long handle_int_119
	.long handle_int_120
	.long handle_int_121
	.long handle_int_122
	.long handle_int_123
	.long handle_int_124
	.long handle_int_125
	.long handle_int_126
	.long handle_int_127
	.long handle_int_128
	.long handle_int_129
	.long handle_int_130
	.long handle_int_131
	.long handle_int_132
	.long handle_int_133
	.long handle_int_134
	.long handle_int_135
	.long handle_int_136
	.long handle_int_137
	.long handle_int_138
	.long handle_int_139
	.long handle_int_140
	.long handle_int_141
	.long handle_int_142
	.long handle_int_143
	.long handle_int_144
	.long handle_int_145
	.long handle_int_146
	.long handle_int_147
	.long handle_int_148
	.long handle_int_149
	.long handle_int_150
	.long handle_int_151
	.long handle_int_152
	.long handle_int_153
	.long handle_int_154
	.long handle_int_155
	.long handle_int_156
	.long handle_int_157
	.long handle_int_158
	.long handle_int_159
	.long handle_int_160
	.long handle_int_161
	.long handle_int_162
	.long handle_int_163
	.long handle_int_164
	.long handle_int_165
	.long handle_int_166
	.long handle_int_167
	.long handle_int_168
	.long handle_int_169
	.long handle_int_170
	.long handle_int_171
	.long handle_int_172
	.long handle_int_173
	.long handle_int_174
	.long handle_int_175
	.long handle_int_176
	.long handle_int_177
	.long handle_int_178
	.long handle_int_179
	.long handle_int_180
	.long handle_int_181
	.long handle_int_182
	.long handle_int_183
	.long handle_int_184
	.long handle_int_185
	.long handle_int_186
	.long handle_int_187
	.long handle_int_188
	.long handle_int_189
	.long handle_int_190
	.long handle_int_191
	.long handle_int_192
	.long handle_int_193
	.long handle_int_194
	.long handle_int_195
	.long handle_int_196
	.long handle_int_197
	.long handle_int_198
	.long handle_int_199
	.long handle_int_200
	.long handle_int_201
	.long handle_int_202
	.long handle_int_203
	.long handle_int_204
	.long handle_int_205
	.long handle_int_206
	.long handle_int_207
	.long handle_int_208
	.long handle_int_209
	.long handle_int_210
	.long handle_int_211
	.long handle_int_212
	.long handle_int_213
	.long handle_int_214
	.long handle_int_215
	.long handle_int_216
	.long handle_int_217
	.long handle_int_218
	.long handle_int_219
	.long handle_int_220
	.long handle_int_221
	.long handle_int_222
	.long handle_int_223
	.long handle_int_224
	.long handle_int_225
	.long handle_int_226
	.long handle_int_227
	.long handle_int_228
	.long handle_int_229
	.long handle_int_230
	.long handle_int_231
	.long handle_int_232
	.long handle_int_233
	.long handle_int_234
	.long handle_int_235
	.long handle_int_236
	.long handle_int_237
	.long handle_int_238
	.long handle_int_239
	.long handle_int_240
	.long handle_int_241
	.long handle_int_242
	.long handle_int_243
	.long handle_int_244
	.long handle_int_245
	.long handle_int_246
	.long handle_int_247
	.long handle_int_248
	.long handle_int_249
	.long handle_int_250
	.long handle_int_251
	.long handle_int_252
	.long handle_int_253
	.long handle_int_254
