from SCons.Script import *

Import('build_arch')
Import('cross_env')

kinclude_paths = ['include']
kinclude_paths = [Dir(path) for path in kinclude_paths]
kernel_ldflags = ['-nostdlib', '--entry=main',
        '--section-start=.text=0xFF000000']
cross_env.Append(CPPPATH=kinclude_paths, LDFLAGS=kernel_ldflags)

subbuilds = [Join_path('arch', build_arch)]

SConscript(Get_subscripts(subbuilds))

# Don't search arch or include for sources, we've added arch.
dir_blacklist = ['^arch$', '^include$']

sources = Get_sources_recursive(CURDIR(), suffixes='.c', blacklist=dir_blacklist)

objects = cross_env.Object(sources)
#print(dir(cross_env))
#cross_env.Ld('chronos.o', objects)
#cross_env.Objcopy('chronos.sym', 'chronos')
