from SCons.Script import *

Import('build_arch')
Import('cross_env')

kinclude_paths = ['include']
kinclude_paths = [Dir(path) for path in kinclude_paths]

cross_env.Append(CPPPATH=kinclude_paths)

subbuilds = [Join_path('arch', build_arch)]

SConscript(Get_subscripts(subbuilds))

# Don't search arch or include for sources, we've added arch.
dir_blacklist = ['arch', 'include']

sources = Get_sources_recursive(CURDIR(), suffixes='.c', blacklist=dir_blacklist)

cross_env.Object(sources)
