from SCons.Script import *

Import('kernel_env')
Import('REAL_CURDIR')

RELOCATE_FLAGS = [
        '-m elf_i386', 
        '-r'
        ] # Wot r these

ARCH_INCLUDE_PATHS = ['include']
ARCH_IGNORE_PATHS = ['^boot$']
ARCH_GCC_SUFFIX = ['.c']

def build_arch_env():
    arch_env = kernel_env.Clone()

    arch_include_paths = Build_include_paths(REAL_CURDIR, ARCH_INCLUDE_PATHS)

    arch_env.Append(CPPPATH=arch_include_paths)

    return arch_env

def build_arch_objects(arch_env):
    sources = Get_sources_recursive(
            CURDIR(), 
            suffixes=ARCH_GCC_SUFFIX,
            blacklist=ARCH_IGNORE_PATHS
            )
    return arch_env.Object(sources)

arch_env = build_arch_env()

build_arch_objects(arch_env)
